__METADATA__
{
  "v3Meta": {
    "objectGuid": "3f62eb89-3ac3-4a26-a155-e96ff6d173b8",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM Merge
VAR
	Counter: INT;
END_VAR
__IMPLEMENTATION__
Counter := Counter + 2 ;
